# Generated by Django 5.1.1 on 2024-09-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='reported_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
