# Generated by Django 5.1.1 on 2024-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
    ]
