# Generated by Django 5.1.1 on 2024-09-14 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_incident_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='user',
            new_name='reported_by',
        ),
        migrations.AddField(
            model_name='incident',
            name='date_occurred',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
